Drag and drop
MirServer/mir-ci pull request #38
Opened 2023-08-23 15:34 UTC by AlanGriffiths

2023-08-24 07:12 UTC, Saviq commented on frame/test_drag_and_drop.py
> +    pass
These missing shouldn't be glossed over, should it?

2023-08-24 07:14 UTC, Saviq commented on frame/test_drag_and_drop.py
> +    pass
Nevermind, I see you took this from the other test. I would probably `import` where it's used instead.

2023-08-24 08:23 UTC, AlanGriffiths commented
@Saviq thanks for the assist. Don't be too hard on this code yet - I'm still experimenting.

2023-08-24 09:30 UTC, Saviq commented
> @Saviq thanks for the assist. Don't be too hard on this code yet - I'm still experimenting.

Not at all, it works! Just wanted to get the icky out of the way :)

2023-08-24 16:18 UTC, Saviq commented on frame/test_drag_and_drop.py
> +    @pytest.mark.deps(debs=('libgtk-4-dev',), pip_pkgs=(('pygobject', 'gi'),))
Since this will likely span the class, you can move this mark up below the `pywayland-scanner` one.

2023-08-25 14:55 UTC, Saviq requested changes
I would consider replacing `EXCHANGE_TYPE_NONE` with just `None`.

You could then simplify things to e.g. `if source_type is not None`, which reads a bit better.

---

When manually driving the app, having selected "Text" on the source, but "Image" on the right, I get "Received pixbuf…", is that expected?

Some nitpicks inline, but fun overall!

2023-08-25 14:55 UTC, Saviq commented on frame/clients/drag_and_drop_demo.py
> +    def __init__(self, source_mode, target_mode, expect):
An easier read, IMO:
```suggestion
class DragDropWindow(Gtk.Window):
    expect = EXCHANGE_TYPE_NONE
    result = EXCHANGE_TYPE_NONE
    
    def __init__(self, source_mode, target_mode, expect=EXCHANGE_TYPE_NONE):
        self.expect = expect
```

2023-08-25 14:55 UTC, Saviq commented on frame/clients/drag_and_drop_demo.py
> +            self.result = EXCHANGE_TYPE_NONE
```suggestion
```

2023-08-25 14:55 UTC, Saviq commented on frame/clients/drag_and_drop_demo.py
> +    try:
This could all be made simpler with [argparse](https://docs.python.org/3/library/argparse.html), but your call.

2023-08-25 14:55 UTC, Saviq commented on frame/clients/drag_and_drop_demo.py
> +
```suggestion
```

2023-08-29 10:01 UTC, AlanGriffiths commented on frame/clients/drag_and_drop_demo.py
> +gi.require_version("Gtk", "3.0")
Changing this breaks the DropArea code I copied in ways that I don't (yet) understand.

2023-08-29 10:02 UTC, AlanGriffiths commented
> When manually driving the app, having selected "Text" on the source, but "Image" on the right, I get "Received pixbuf…", is that expected?

I don't follow why, but changing the types via the buttons doesn't work as as I (or you) expected.

2023-08-30 08:38 UTC, Saviq approved these changes
Cool :)

2023-08-30 08:48 UTC, merged