Tests for updating the display configuration while the server is running
MirServer/mir-ci pull request #59
Opened 2023-10-19 21:27 UTC by mattkae

## What's new?
- Added a single test for updating the display configuration while a display server is running
- This does not work with ubuntu frame or mir-kiosk as they don't respect the environment variable
- We can add more tests if you think this is a viable route :+1:

2023-10-23 15:24 UTC, Saviq requested changes
Some tweaks inline

2023-10-23 15:24 UTC, Saviq commented on mir-ci/mir_ci/display_server.py
> +
I would rather we add `env: Dict[str, str]` to `__init__()`, just like we have with `Program`:

https://github.com/MirServer/mir-ci/blob/a453ae04cfc644b62d785de22405596e6505736c/mir-ci/mir_ci/program.py#L43

2023-10-23 15:24 UTC, Saviq commented on mir-ci/mir_ci/test_display_configuration.py
> +            apps.mir_demo_server(),
Leave a `TODO` please to test other servers, too.

2023-10-23 15:24 UTC, Saviq commented on mir-ci/mir_ci/test_display_configuration.py
> +            pass
Best use a [tempfile.NamedTemporaryFile](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) as a context manager (you will need to "enter" it before it gets a name).

2023-11-02 12:08 UTC, AlanGriffiths approved these changes
We need more tests like this

2023-11-02 12:13 UTC, Saviq approved these changes
Not sure why you needed the decorator on each test rather than the class, but OK :)

2023-11-02 12:29 UTC, merged